//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinal.Maps {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Maps.IServicioEvento")]
    public interface IServicioEvento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaLugar", ReplyAction="http://tempuri.org/IServicioEvento/AltaLugarResponse")]
        void AltaLugar(EntidadesCompartidas.Lugar l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarLugar", ReplyAction="http://tempuri.org/IServicioEvento/ModificarLugarResponse")]
        void ModificarLugar(EntidadesCompartidas.Lugar l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarLugar", ReplyAction="http://tempuri.org/IServicioEvento/BuscarLugarResponse")]
        EntidadesCompartidas.Lugar BuscarLugar(string NombreLugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BajaLugar", ReplyAction="http://tempuri.org/IServicioEvento/BajaLugarResponse")]
        void BajaLugar(EntidadesCompartidas.Lugar l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarLugares", ReplyAction="http://tempuri.org/IServicioEvento/ListarLugaresResponse")]
        EntidadesCompartidas.Lugar[] ListarLugares();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarLugaresDisponibles", ReplyAction="http://tempuri.org/IServicioEvento/ListarLugaresDisponiblesResponse")]
        EntidadesCompartidas.Lugar[] ListarLugaresDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarLugaresCiudad", ReplyAction="http://tempuri.org/IServicioEvento/ListarLugaresCiudadResponse")]
        EntidadesCompartidas.Lugar[] ListarLugaresCiudad(string pNombreCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarMapaLugar", ReplyAction="http://tempuri.org/IServicioEvento/BuscarMapaLugarResponse")]
        EntidadesCompartidas.Lugar BuscarMapaLugar(int IdMapa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaArea", ReplyAction="http://tempuri.org/IServicioEvento/AltaAreaResponse")]
        void AltaArea(EntidadesCompartidas.Area a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarArea", ReplyAction="http://tempuri.org/IServicioEvento/ModificarAreaResponse")]
        void ModificarArea(EntidadesCompartidas.Area a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarArea", ReplyAction="http://tempuri.org/IServicioEvento/BuscarAreaResponse")]
        EntidadesCompartidas.Area BuscarArea(int IdArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarAreaPorNombre", ReplyAction="http://tempuri.org/IServicioEvento/BuscarAreaPorNombreResponse")]
        EntidadesCompartidas.Area BuscarAreaPorNombre(string NombreArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaPuntodeArea", ReplyAction="http://tempuri.org/IServicioEvento/AltaPuntodeAreaResponse")]
        void AltaPuntodeArea(EntidadesCompartidas.Area a, EntidadesCompartidas.Punto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BajaArea", ReplyAction="http://tempuri.org/IServicioEvento/BajaAreaResponse")]
        void BajaArea(EntidadesCompartidas.Area a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarAreasDeMapa", ReplyAction="http://tempuri.org/IServicioEvento/ListarAreasDeMapaResponse")]
        EntidadesCompartidas.Area[] ListarAreasDeMapa(int IdMapa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarPuntosDeUnArea", ReplyAction="http://tempuri.org/IServicioEvento/ListarPuntosDeUnAreaResponse")]
        EntidadesCompartidas.Punto[] ListarPuntosDeUnArea(EntidadesCompartidas.Area a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaAlquiler", ReplyAction="http://tempuri.org/IServicioEvento/AltaAlquilerResponse")]
        void AltaAlquiler(EntidadesCompartidas.Alquiler e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BajaAlquiler", ReplyAction="http://tempuri.org/IServicioEvento/BajaAlquilerResponse")]
        void BajaAlquiler(EntidadesCompartidas.Alquiler e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarAlquiler", ReplyAction="http://tempuri.org/IServicioEvento/BuscarAlquilerResponse")]
        EntidadesCompartidas.Alquiler BuscarAlquiler(int IdAlquiler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarAlquileres", ReplyAction="http://tempuri.org/IServicioEvento/ListarAlquileresResponse")]
        EntidadesCompartidas.Alquiler[] ListarAlquileres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarAlquileresArea", ReplyAction="http://tempuri.org/IServicioEvento/ListarAlquileresAreaResponse")]
        EntidadesCompartidas.Alquiler[] ListarAlquileresArea(int IdArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarAlquileresOrganizador", ReplyAction="http://tempuri.org/IServicioEvento/ListarAlquileresOrganizadorResponse")]
        EntidadesCompartidas.Alquiler[] ListarAlquileresOrganizador(string Ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaMapa", ReplyAction="http://tempuri.org/IServicioEvento/AltaMapaResponse")]
        void AltaMapa(EntidadesCompartidas.Mapa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarMapa", ReplyAction="http://tempuri.org/IServicioEvento/ModificarMapaResponse")]
        void ModificarMapa(EntidadesCompartidas.Mapa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarMapa", ReplyAction="http://tempuri.org/IServicioEvento/BuscarMapaResponse")]
        EntidadesCompartidas.Mapa BuscarMapa(int IdMapa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BajaMapa", ReplyAction="http://tempuri.org/IServicioEvento/BajaMapaResponse")]
        void BajaMapa(EntidadesCompartidas.Mapa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaUbicacion", ReplyAction="http://tempuri.org/IServicioEvento/AltaUbicacionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Ciudad))]
        void AltaUbicacion(EntidadesCompartidas.Ubicacion U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarUbicacion", ReplyAction="http://tempuri.org/IServicioEvento/ModificarUbicacionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Ciudad))]
        void ModificarUbicacion(EntidadesCompartidas.Ubicacion U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/EliminarUbicacion", ReplyAction="http://tempuri.org/IServicioEvento/EliminarUbicacionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Ciudad))]
        void EliminarUbicacion(EntidadesCompartidas.Ubicacion U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarPais", ReplyAction="http://tempuri.org/IServicioEvento/BuscarPaisResponse")]
        EntidadesCompartidas.Pais BuscarPais(string pNombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarCiudad", ReplyAction="http://tempuri.org/IServicioEvento/BuscarCiudadResponse")]
        EntidadesCompartidas.Ciudad BuscarCiudad(string pNombrePais, EntidadesCompartidas.Pais UnPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarCiudades", ReplyAction="http://tempuri.org/IServicioEvento/ListarCiudadesResponse")]
        EntidadesCompartidas.Ciudad[] ListarCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarPais", ReplyAction="http://tempuri.org/IServicioEvento/ListarPaisResponse")]
        EntidadesCompartidas.Pais[] ListarPais();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarCiudadesPais", ReplyAction="http://tempuri.org/IServicioEvento/ListarCiudadesPaisResponse")]
        EntidadesCompartidas.Ciudad[] ListarCiudadesPais(EntidadesCompartidas.Pais UnPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaUsuario", ReplyAction="http://tempuri.org/IServicioEvento/AltaUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        void AltaUsuario(EntidadesCompartidas.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarUsuario", ReplyAction="http://tempuri.org/IServicioEvento/ModificarUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        void ModificarUsuario(EntidadesCompartidas.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/EliminarUsuario", ReplyAction="http://tempuri.org/IServicioEvento/EliminarUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        void EliminarUsuario(EntidadesCompartidas.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarUsuario", ReplyAction="http://tempuri.org/IServicioEvento/BuscarUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        EntidadesCompartidas.Usuario BuscarUsuario(string pDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/Login", ReplyAction="http://tempuri.org/IServicioEvento/LoginResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        EntidadesCompartidas.Usuario Login(string nomUsu, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarAdmin", ReplyAction="http://tempuri.org/IServicioEvento/ListarAdminResponse")]
        EntidadesCompartidas.Admin[] ListarAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarDueños", ReplyAction="http://tempuri.org/IServicioEvento/ListarDueñosResponse")]
        EntidadesCompartidas.Dueño[] ListarDueños();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarOrganizadores", ReplyAction="http://tempuri.org/IServicioEvento/ListarOrganizadoresResponse")]
        EntidadesCompartidas.Organizador[] ListarOrganizadores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarClientes", ReplyAction="http://tempuri.org/IServicioEvento/ListarClientesResponse")]
        EntidadesCompartidas.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaEvento", ReplyAction="http://tempuri.org/IServicioEvento/AltaEventoResponse")]
        void AltaEvento(EntidadesCompartidas.Evento p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ComprobarEstadoEvento", ReplyAction="http://tempuri.org/IServicioEvento/ComprobarEstadoEventoResponse")]
        void ComprobarEstadoEvento(EntidadesCompartidas.Evento UnEvento, System.DateTime fecha1, System.DateTime fecha2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BajaEvento", ReplyAction="http://tempuri.org/IServicioEvento/BajaEventoResponse")]
        void BajaEvento(EntidadesCompartidas.Evento e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarEvento", ReplyAction="http://tempuri.org/IServicioEvento/BuscarEventoResponse")]
        EntidadesCompartidas.Evento BuscarEvento(int IdEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarCategoria", ReplyAction="http://tempuri.org/IServicioEvento/BuscarCategoriaResponse")]
        EntidadesCompartidas.Categoria BuscarCategoria(string NombreCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarCategorias", ReplyAction="http://tempuri.org/IServicioEvento/ListarCategoriasResponse")]
        EntidadesCompartidas.Categoria[] ListarCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarEventosOrdenFecha", ReplyAction="http://tempuri.org/IServicioEvento/ListarEventosOrdenFechaResponse")]
        EntidadesCompartidas.Evento[] ListarEventosOrdenFecha();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarEventosOrganizador", ReplyAction="http://tempuri.org/IServicioEvento/ListarEventosOrganizadorResponse")]
        EntidadesCompartidas.Evento[] ListarEventosOrganizador(string CiOrganizador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarEventosReservados", ReplyAction="http://tempuri.org/IServicioEvento/ListarEventosReservadosResponse")]
        EntidadesCompartidas.Evento[] ListarEventosReservados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarEventosxArea", ReplyAction="http://tempuri.org/IServicioEvento/ListarEventosxAreaResponse")]
        EntidadesCompartidas.Evento[] ListarEventosxArea(int IdArea);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEventoChannel : MVCFinal.Maps.IServicioEvento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEventoClient : System.ServiceModel.ClientBase<MVCFinal.Maps.IServicioEvento>, MVCFinal.Maps.IServicioEvento {
        
        public ServicioEventoClient() {
        }
        
        public ServicioEventoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEventoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEventoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEventoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AltaLugar(EntidadesCompartidas.Lugar l) {
            base.Channel.AltaLugar(l);
        }
        
        public void ModificarLugar(EntidadesCompartidas.Lugar l) {
            base.Channel.ModificarLugar(l);
        }
        
        public EntidadesCompartidas.Lugar BuscarLugar(string NombreLugar) {
            return base.Channel.BuscarLugar(NombreLugar);
        }
        
        public void BajaLugar(EntidadesCompartidas.Lugar l) {
            base.Channel.BajaLugar(l);
        }
        
        public EntidadesCompartidas.Lugar[] ListarLugares() {
            return base.Channel.ListarLugares();
        }
        
        public EntidadesCompartidas.Lugar[] ListarLugaresDisponibles() {
            return base.Channel.ListarLugaresDisponibles();
        }
        
        public EntidadesCompartidas.Lugar[] ListarLugaresCiudad(string pNombreCiudad) {
            return base.Channel.ListarLugaresCiudad(pNombreCiudad);
        }
        
        public EntidadesCompartidas.Lugar BuscarMapaLugar(int IdMapa) {
            return base.Channel.BuscarMapaLugar(IdMapa);
        }
        
        public void AltaArea(EntidadesCompartidas.Area a) {
            base.Channel.AltaArea(a);
        }
        
        public void ModificarArea(EntidadesCompartidas.Area a) {
            base.Channel.ModificarArea(a);
        }
        
        public EntidadesCompartidas.Area BuscarArea(int IdArea) {
            return base.Channel.BuscarArea(IdArea);
        }
        
        public EntidadesCompartidas.Area BuscarAreaPorNombre(string NombreArea) {
            return base.Channel.BuscarAreaPorNombre(NombreArea);
        }
        
        public void AltaPuntodeArea(EntidadesCompartidas.Area a, EntidadesCompartidas.Punto p) {
            base.Channel.AltaPuntodeArea(a, p);
        }
        
        public void BajaArea(EntidadesCompartidas.Area a) {
            base.Channel.BajaArea(a);
        }
        
        public EntidadesCompartidas.Area[] ListarAreasDeMapa(int IdMapa) {
            return base.Channel.ListarAreasDeMapa(IdMapa);
        }
        
        public EntidadesCompartidas.Punto[] ListarPuntosDeUnArea(EntidadesCompartidas.Area a) {
            return base.Channel.ListarPuntosDeUnArea(a);
        }
        
        public void AltaAlquiler(EntidadesCompartidas.Alquiler e) {
            base.Channel.AltaAlquiler(e);
        }
        
        public void BajaAlquiler(EntidadesCompartidas.Alquiler e) {
            base.Channel.BajaAlquiler(e);
        }
        
        public EntidadesCompartidas.Alquiler BuscarAlquiler(int IdAlquiler) {
            return base.Channel.BuscarAlquiler(IdAlquiler);
        }
        
        public EntidadesCompartidas.Alquiler[] ListarAlquileres() {
            return base.Channel.ListarAlquileres();
        }
        
        public EntidadesCompartidas.Alquiler[] ListarAlquileresArea(int IdArea) {
            return base.Channel.ListarAlquileresArea(IdArea);
        }
        
        public EntidadesCompartidas.Alquiler[] ListarAlquileresOrganizador(string Ci) {
            return base.Channel.ListarAlquileresOrganizador(Ci);
        }
        
        public void AltaMapa(EntidadesCompartidas.Mapa m) {
            base.Channel.AltaMapa(m);
        }
        
        public void ModificarMapa(EntidadesCompartidas.Mapa m) {
            base.Channel.ModificarMapa(m);
        }
        
        public EntidadesCompartidas.Mapa BuscarMapa(int IdMapa) {
            return base.Channel.BuscarMapa(IdMapa);
        }
        
        public void BajaMapa(EntidadesCompartidas.Mapa m) {
            base.Channel.BajaMapa(m);
        }
        
        public void AltaUbicacion(EntidadesCompartidas.Ubicacion U) {
            base.Channel.AltaUbicacion(U);
        }
        
        public void ModificarUbicacion(EntidadesCompartidas.Ubicacion U) {
            base.Channel.ModificarUbicacion(U);
        }
        
        public void EliminarUbicacion(EntidadesCompartidas.Ubicacion U) {
            base.Channel.EliminarUbicacion(U);
        }
        
        public EntidadesCompartidas.Pais BuscarPais(string pNombre) {
            return base.Channel.BuscarPais(pNombre);
        }
        
        public EntidadesCompartidas.Ciudad BuscarCiudad(string pNombrePais, EntidadesCompartidas.Pais UnPais) {
            return base.Channel.BuscarCiudad(pNombrePais, UnPais);
        }
        
        public EntidadesCompartidas.Ciudad[] ListarCiudades() {
            return base.Channel.ListarCiudades();
        }
        
        public EntidadesCompartidas.Pais[] ListarPais() {
            return base.Channel.ListarPais();
        }
        
        public EntidadesCompartidas.Ciudad[] ListarCiudadesPais(EntidadesCompartidas.Pais UnPais) {
            return base.Channel.ListarCiudadesPais(UnPais);
        }
        
        public void AltaUsuario(EntidadesCompartidas.Usuario U) {
            base.Channel.AltaUsuario(U);
        }
        
        public void ModificarUsuario(EntidadesCompartidas.Usuario U) {
            base.Channel.ModificarUsuario(U);
        }
        
        public void EliminarUsuario(EntidadesCompartidas.Usuario U) {
            base.Channel.EliminarUsuario(U);
        }
        
        public EntidadesCompartidas.Usuario BuscarUsuario(string pDoc) {
            return base.Channel.BuscarUsuario(pDoc);
        }
        
        public EntidadesCompartidas.Usuario Login(string nomUsu, string pass) {
            return base.Channel.Login(nomUsu, pass);
        }
        
        public EntidadesCompartidas.Admin[] ListarAdmin() {
            return base.Channel.ListarAdmin();
        }
        
        public EntidadesCompartidas.Dueño[] ListarDueños() {
            return base.Channel.ListarDueños();
        }
        
        public EntidadesCompartidas.Organizador[] ListarOrganizadores() {
            return base.Channel.ListarOrganizadores();
        }
        
        public EntidadesCompartidas.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public void AltaEvento(EntidadesCompartidas.Evento p) {
            base.Channel.AltaEvento(p);
        }
        
        public void ComprobarEstadoEvento(EntidadesCompartidas.Evento UnEvento, System.DateTime fecha1, System.DateTime fecha2) {
            base.Channel.ComprobarEstadoEvento(UnEvento, fecha1, fecha2);
        }
        
        public void BajaEvento(EntidadesCompartidas.Evento e) {
            base.Channel.BajaEvento(e);
        }
        
        public EntidadesCompartidas.Evento BuscarEvento(int IdEvento) {
            return base.Channel.BuscarEvento(IdEvento);
        }
        
        public EntidadesCompartidas.Categoria BuscarCategoria(string NombreCategoria) {
            return base.Channel.BuscarCategoria(NombreCategoria);
        }
        
        public EntidadesCompartidas.Categoria[] ListarCategorias() {
            return base.Channel.ListarCategorias();
        }
        
        public EntidadesCompartidas.Evento[] ListarEventosOrdenFecha() {
            return base.Channel.ListarEventosOrdenFecha();
        }
        
        public EntidadesCompartidas.Evento[] ListarEventosOrganizador(string CiOrganizador) {
            return base.Channel.ListarEventosOrganizador(CiOrganizador);
        }
        
        public EntidadesCompartidas.Evento[] ListarEventosReservados() {
            return base.Channel.ListarEventosReservados();
        }
        
        public EntidadesCompartidas.Evento[] ListarEventosxArea(int IdArea) {
            return base.Channel.ListarEventosxArea(IdArea);
        }
    }
}
