//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinal.Maps {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Maps.IServicioEvento")]
    public interface IServicioEvento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaLugar", ReplyAction="http://tempuri.org/IServicioEvento/AltaLugarResponse")]
        void AltaLugar(EntidadesCompartidas.Lugar l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarLugar", ReplyAction="http://tempuri.org/IServicioEvento/ModificarLugarResponse")]
        void ModificarLugar(EntidadesCompartidas.Lugar l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarLugarxId", ReplyAction="http://tempuri.org/IServicioEvento/BuscarLugarxIdResponse")]
        EntidadesCompartidas.Lugar BuscarLugarxId(int IdLugar, string NombreCiudad, string NombrePais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BajaLugar", ReplyAction="http://tempuri.org/IServicioEvento/BajaLugarResponse")]
        void BajaLugar(EntidadesCompartidas.Lugar l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaMapa", ReplyAction="http://tempuri.org/IServicioEvento/AltaMapaResponse")]
        void AltaMapa(EntidadesCompartidas.Mapa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarMapa", ReplyAction="http://tempuri.org/IServicioEvento/ModificarMapaResponse")]
        void ModificarMapa(EntidadesCompartidas.Mapa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarMapa", ReplyAction="http://tempuri.org/IServicioEvento/BuscarMapaResponse")]
        EntidadesCompartidas.Mapa BuscarMapa(int IdMapa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BajaMapa", ReplyAction="http://tempuri.org/IServicioEvento/BajaMapaResponse")]
        void BajaMapa(EntidadesCompartidas.Mapa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaUbicacion", ReplyAction="http://tempuri.org/IServicioEvento/AltaUbicacionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Ciudad))]
        void AltaUbicacion(EntidadesCompartidas.Ubicacion U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarUbicacion", ReplyAction="http://tempuri.org/IServicioEvento/ModificarUbicacionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Ciudad))]
        void ModificarUbicacion(EntidadesCompartidas.Ubicacion U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/EliminarUbicacion", ReplyAction="http://tempuri.org/IServicioEvento/EliminarUbicacionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Ciudad))]
        void EliminarUbicacion(EntidadesCompartidas.Ubicacion U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarPais", ReplyAction="http://tempuri.org/IServicioEvento/BuscarPaisResponse")]
        EntidadesCompartidas.Pais BuscarPais(string pNombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarCiudad", ReplyAction="http://tempuri.org/IServicioEvento/BuscarCiudadResponse")]
        EntidadesCompartidas.Ciudad BuscarCiudad(string pNombrePais, EntidadesCompartidas.Pais UnPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarCiudades", ReplyAction="http://tempuri.org/IServicioEvento/ListarCiudadesResponse")]
        EntidadesCompartidas.Ciudad[] ListarCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarPais", ReplyAction="http://tempuri.org/IServicioEvento/ListarPaisResponse")]
        EntidadesCompartidas.Pais[] ListarPais();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarCiudadesPais", ReplyAction="http://tempuri.org/IServicioEvento/ListarCiudadesPaisResponse")]
        EntidadesCompartidas.Ciudad[] ListarCiudadesPais(EntidadesCompartidas.Pais UnPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/AltaUsuario", ReplyAction="http://tempuri.org/IServicioEvento/AltaUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        void AltaUsuario(EntidadesCompartidas.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ModificarUsuario", ReplyAction="http://tempuri.org/IServicioEvento/ModificarUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        void ModificarUsuario(EntidadesCompartidas.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/EliminarUsuario", ReplyAction="http://tempuri.org/IServicioEvento/EliminarUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        void EliminarUsuario(EntidadesCompartidas.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/BuscarUsuario", ReplyAction="http://tempuri.org/IServicioEvento/BuscarUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        EntidadesCompartidas.Usuario BuscarUsuario(string pDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/Login", ReplyAction="http://tempuri.org/IServicioEvento/LoginResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Dueño))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadesCompartidas.Organizador))]
        EntidadesCompartidas.Usuario Login(string nomUsu, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarAdmin", ReplyAction="http://tempuri.org/IServicioEvento/ListarAdminResponse")]
        EntidadesCompartidas.Admin[] ListarAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarDueños", ReplyAction="http://tempuri.org/IServicioEvento/ListarDueñosResponse")]
        EntidadesCompartidas.Dueño[] ListarDueños();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarOrganizadores", ReplyAction="http://tempuri.org/IServicioEvento/ListarOrganizadoresResponse")]
        EntidadesCompartidas.Organizador[] ListarOrganizadores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvento/ListarClientes", ReplyAction="http://tempuri.org/IServicioEvento/ListarClientesResponse")]
        EntidadesCompartidas.Cliente[] ListarClientes();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEventoChannel : MVCFinal.Maps.IServicioEvento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEventoClient : System.ServiceModel.ClientBase<MVCFinal.Maps.IServicioEvento>, MVCFinal.Maps.IServicioEvento {
        
        public ServicioEventoClient() {
        }
        
        public ServicioEventoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEventoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEventoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEventoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AltaLugar(EntidadesCompartidas.Lugar l) {
            base.Channel.AltaLugar(l);
        }
        
        public void ModificarLugar(EntidadesCompartidas.Lugar l) {
            base.Channel.ModificarLugar(l);
        }
        
        public EntidadesCompartidas.Lugar BuscarLugarxId(int IdLugar, string NombreCiudad, string NombrePais) {
            return base.Channel.BuscarLugarxId(IdLugar, NombreCiudad, NombrePais);
        }
        
        public void BajaLugar(EntidadesCompartidas.Lugar l) {
            base.Channel.BajaLugar(l);
        }
        
        public void AltaMapa(EntidadesCompartidas.Mapa m) {
            base.Channel.AltaMapa(m);
        }
        
        public void ModificarMapa(EntidadesCompartidas.Mapa m) {
            base.Channel.ModificarMapa(m);
        }
        
        public EntidadesCompartidas.Mapa BuscarMapa(int IdMapa) {
            return base.Channel.BuscarMapa(IdMapa);
        }
        
        public void BajaMapa(EntidadesCompartidas.Mapa m) {
            base.Channel.BajaMapa(m);
        }
        
        public void AltaUbicacion(EntidadesCompartidas.Ubicacion U) {
            base.Channel.AltaUbicacion(U);
        }
        
        public void ModificarUbicacion(EntidadesCompartidas.Ubicacion U) {
            base.Channel.ModificarUbicacion(U);
        }
        
        public void EliminarUbicacion(EntidadesCompartidas.Ubicacion U) {
            base.Channel.EliminarUbicacion(U);
        }
        
        public EntidadesCompartidas.Pais BuscarPais(string pNombre) {
            return base.Channel.BuscarPais(pNombre);
        }
        
        public EntidadesCompartidas.Ciudad BuscarCiudad(string pNombrePais, EntidadesCompartidas.Pais UnPais) {
            return base.Channel.BuscarCiudad(pNombrePais, UnPais);
        }
        
        public EntidadesCompartidas.Ciudad[] ListarCiudades() {
            return base.Channel.ListarCiudades();
        }
        
        public EntidadesCompartidas.Pais[] ListarPais() {
            return base.Channel.ListarPais();
        }
        
        public EntidadesCompartidas.Ciudad[] ListarCiudadesPais(EntidadesCompartidas.Pais UnPais) {
            return base.Channel.ListarCiudadesPais(UnPais);
        }
        
        public void AltaUsuario(EntidadesCompartidas.Usuario U) {
            base.Channel.AltaUsuario(U);
        }
        
        public void ModificarUsuario(EntidadesCompartidas.Usuario U) {
            base.Channel.ModificarUsuario(U);
        }
        
        public void EliminarUsuario(EntidadesCompartidas.Usuario U) {
            base.Channel.EliminarUsuario(U);
        }
        
        public EntidadesCompartidas.Usuario BuscarUsuario(string pDoc) {
            return base.Channel.BuscarUsuario(pDoc);
        }
        
        public EntidadesCompartidas.Usuario Login(string nomUsu, string pass) {
            return base.Channel.Login(nomUsu, pass);
        }
        
        public EntidadesCompartidas.Admin[] ListarAdmin() {
            return base.Channel.ListarAdmin();
        }
        
        public EntidadesCompartidas.Dueño[] ListarDueños() {
            return base.Channel.ListarDueños();
        }
        
        public EntidadesCompartidas.Organizador[] ListarOrganizadores() {
            return base.Channel.ListarOrganizadores();
        }
        
        public EntidadesCompartidas.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
    }
}
